# Generated by Django 5.0.4 on 2024-04-14 18:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Título')),
                ('link', models.URLField(verbose_name='Enlace')),
                ('image', models.ImageField(upload_to='certificates', verbose_name='Miniatura')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(default='null', max_length=254, verbose_name='Correo eléctronico')),
                ('title', models.CharField(default='null', max_length=150, verbose_name='Título')),
                ('message', models.TextField(default='null', verbose_name='Mensaje')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Recibido el')),
            ],
            options={
                'verbose_name': 'Solicitud de contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=40, verbose_name='Cargo')),
                ('company', models.CharField(max_length=100, verbose_name='Compañía')),
                ('since', models.DateField(verbose_name='Desde')),
                ('to', models.DateField(verbose_name='Hasta')),
                ('functions', ckeditor.fields.RichTextField(verbose_name='Funciones')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('resumen', models.CharField(default='Desarrollo de software', max_length=50, verbose_name='Resumen')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='projects', verbose_name='Foto principal')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('belongsTo', models.CharField(max_length=255, verbose_name='Pertenece a')),
                ('description', models.CharField(default='null', max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Imagen de proyecto',
                'verbose_name_plural': 'Imagenes de proyectos',
            },
        ),
    ]
