# Generated by Django 5.0 on 2024-01-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='', verbose_name='Foto principal')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
